'use strict';
const {cleanEdits,keptSegments}=require('../../engine/edit-plan.cjs');
const $=id=>document.getElementById(id),api=(...a)=>window.cleartake.invoke(...a);
let project=null,edits=null,history=[],future=[],source=null,capture=null,peaks=[],saveTimer,saveChain=Promise.resolve(),previewStop=null;
const video=$('screen-video'),voice=$('voice-audio'),camera=$('camera-video');
const copy=x=>JSON.parse(JSON.stringify(x));
const time=s=>{s=Math.max(0,Number(s)||0);return `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,7000);}
function action(id,fn){$(id).addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>toast(e.message)));}
function view(name){for(const v of ['home','recording','editor'])$(v+'-view').hidden=v!==name;$('page-title').textContent=name==='editor'?'Make room for the good parts.':name==='recording'?'Your take is rolling.':'Let’s make a clear take.';$('home-nav').classList.toggle('active',name==='home');$('edit-nav').classList.toggle('active',name==='editor');$('open-project').disabled=name==='recording';$('home-nav').disabled=name==='recording';$('edit-nav').disabled=!project||name==='recording';}
window.cleartake.onProgress(({message,progress})=>{$('job-panel').hidden=!message;document.body.classList.toggle('busy',!!message);$('job-text').textContent=message;if(progress===0)$('job-progress').removeAttribute('value');else $('job-progress').value=progress??0;});
action('cancel-job',()=>api('job:cancel'));
function stopPlayback(){video.pause();voice.pause();camera.pause();$('play').textContent='▶ Play edit';}
async function saveNow(){clearTimeout(saveTimer);if(!project)return;const id=project.id,snapshot=copy(edits),name=$('project-name').value;saveChain=saveChain.catch(()=>{}).then(()=>api('project:save',id,snapshot,name));try{await saveChain;if(project?.id===id)$('save-state').textContent='Saved on this computer';}catch(e){$('save-state').textContent='Save failed';throw e;}}
function changed(fn){history.push(copy(edits));if(history.length>100)history.shift();future=[];fn();edits=cleanEdits(edits,project.duration);refresh();$('save-state').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveNow().catch(e=>toast(e.message)),450);}
async function openProject(p){if(!p)return;if(p.state!=='ready')throw new Error('This recording is incomplete. Use Show files from the recordings list to recover its original media.');await saveNow();stopPlayback();project=p;edits=cleanEdits(p.edits,p.duration);history=[];future=[];peaks=[];$('project-name').value=p.name;video.src=p.urls.screen;if(p.urls.mic)voice.src=p.urls.mic;else voice.removeAttribute('src');if(p.urls.camera)camera.src=p.urls.camera;else camera.removeAttribute('src');$('scrub').max=p.duration;$('range-start').value=0;$('range-end').value=Math.min(2,p.duration).toFixed(2);$('preview-original').checked=false;view('editor');refresh();const id=p.id;api('waveform',id).then(data=>{if(project?.id===id){peaks=data;drawTimeline();}}).catch(()=>{if(project?.id===id)toast('Waveform unavailable. You can still enter start and end times.');});}
async function listProjects(){const list=await api('projects:list');$('project-list').replaceChildren();if(!list.length){const p=document.createElement('p');p.className='muted';p.textContent='Your first recording will appear here.';$('project-list').append(p);}for(const p of list){const button=document.createElement('button');button.className='project-tile';const title=document.createElement('b'),detail=document.createElement('small');title.textContent=p.name;detail.textContent=`${time(p.duration)} · ${new Date(p.created).toLocaleDateString()}${p.state==='ready'?'':' · Incomplete — show files'}`;button.append(title,detail);button.onclick=()=>Promise.resolve(p.state==='ready'?openProject(p):api('project:reveal',p.id)).catch(e=>toast(e.message));$('project-list').append(button);}}
action('home-nav',async()=>{stopPlayback();await saveNow();view('home');await listProjects();});action('edit-nav',()=>view('editor'));action('refresh-projects',listProjects);action('open-project',async()=>openProject(await api('project:open')));action('import-video',async()=>openProject(await api('project:import')));action('save-project',saveNow);action('show-files',()=>api('project:reveal',project.id));$('project-name').onchange=()=>saveNow().catch(e=>toast(e.message));
action('select-screen',async()=>{const rows=await api('sources');$('sources').replaceChildren();for(const row of rows){const b=document.createElement('button'),img=document.createElement('img'),label=document.createElement('span');img.src=row.image;img.alt='';label.textContent=row.name;b.className='source-card';b.append(img,label);b.onclick=async()=>{try{await api('choose-source',row.id,$('use-system').checked);source=row;$('source-name').textContent=row.name;$('source-dialog').close();}catch(e){toast(e.message);}};$('sources').append(b);}$('source-dialog').showModal();});action('close-source',()=>$('source-dialog').close());
async function devices(){const selected=$('mic-device').value;const list=await navigator.mediaDevices.enumerateDevices();$('mic-device').replaceChildren(new Option('Default microphone',''));list.filter(d=>d.kind==='audioinput'&&d.deviceId&&d.deviceId!=='default').forEach((d,i)=>$('mic-device').add(new Option(d.label||`Microphone ${i+1}`,d.deviceId)));$('mic-device').value=selected;}
function mime(track){return (track==='mic'?['audio/webm;codecs=opus','audio/webm']:['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm']).find(v=>MediaRecorder.isTypeSupported(v));}
async function startRecording(){if(!source)throw new Error('Choose a screen or window first.');$('record').disabled=true;const streams={};let p;
try{await api('choose-source',source.id,$('use-system').checked);streams.screen=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:30},audio:$('use-system').checked});if($('use-mic').checked)streams.mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false,...($('mic-device').value?{deviceId:{exact:$('mic-device').value}}:{})},video:false});if($('use-camera').checked)streams.camera=await navigator.mediaDevices.getUserMedia({video:{width:1280,height:720},audio:false});await saveNow();p=await api('record:begin',$('record-name').value||'Untitled recording');
const c={id:p.id,streams,recorders:[],queue:Promise.resolve(),error:null,started:performance.now(),elapsed:0,paused:false,stopping:false,auto:$('auto-scan').checked};capture=c;
for(const [track,stream] of Object.entries(streams)){const recorder=new MediaRecorder(stream,{mimeType:mime(track),...(track==='mic'?{audioBitsPerSecond:128000}:{videoBitsPerSecond:6000000})});recorder.ondataavailable=event=>{if(event.data.size)c.queue=c.queue.then(async()=>api('record:chunk',c.id,track,await event.data.arrayBuffer())).catch(error=>{c.error=error;});};recorder.onerror=event=>{c.error=event.error||new Error('Recording failed.');stopRecording().catch(e=>toast(e.message));};c.recorders.push(recorder);}c.recorders.forEach(r=>r.start(1000));streams.screen.getVideoTracks()[0].onended=()=>stopRecording().catch(e=>toast(e.message));c.timer=setInterval(()=>{$('recording-clock').textContent=time((c.elapsed+(c.paused?0:performance.now()-c.started))/1000);},250);$('pause-record').textContent='Pause';$('recording-heading').textContent='Recording your take';$('recording-clock').textContent='00:00';view('recording');devices().catch(()=>{});if($('use-system').checked&&!streams.screen.getAudioTracks().length)toast('Computer audio was not provided by macOS. Your selected microphone is still being recorded.');
}catch(e){Object.values(streams).forEach(s=>s.getTracks().forEach(t=>t.stop()));if(p)await api('record:abandon',p.id);capture=null;throw e;}finally{$('record').disabled=false;}}
async function stopRecording(){const c=capture;if(!c||c.stopping)return;c.stopping=true;clearInterval(c.timer);$('stop-record').disabled=true;$('pause-record').disabled=true;
try{await Promise.all(c.recorders.map(r=>new Promise(resolve=>{if(r.state==='inactive')return resolve();r.addEventListener('stop',resolve,{once:true});r.stop();})));Object.values(c.streams).forEach(s=>s.getTracks().forEach(t=>t.stop()));await c.queue;if(c.error)throw c.error;const p=await api('record:finish',c.id);capture=null;await openProject(p);if(c.auto)await scan();}catch(e){await api('record:abandon',c.id).catch(()=>{});capture=null;if(!project)view('home');throw e;}finally{$('stop-record').disabled=false;$('pause-record').disabled=false;}}
action('record',startRecording);action('stop-record',stopRecording);action('pause-record',()=>{const c=capture;if(!c||c.stopping)return;if(c.paused){c.recorders.forEach(r=>r.resume());c.started=performance.now();}else{c.recorders.forEach(r=>r.pause());c.elapsed+=performance.now()-c.started;}c.paused=!c.paused;$('pause-record').textContent=c.paused?'Resume':'Pause';$('recording-heading').textContent=c.paused?'Recording paused':'Recording your take';});
const fields={'trim-start':'start','trim-end':'end',speed:'speed',aspect:'aspect',background:'background',padding:'padding',zoom:'zoom','voice-volume':'voiceVolume','system-volume':'systemVolume',noise:'noise','show-camera':'camera','camera-corner':'cameraCorner','camera-size':'cameraSize',title:'title'};
for(const [id,key] of Object.entries(fields))$(id).addEventListener('change',()=>changed(()=>{edits[key]=$(id).type==='checkbox'?$(id).checked:$(id).value;}));
function refresh(){if(!project)return;for(const [id,key] of Object.entries(fields)){if($(id).type==='checkbox')$(id).checked=edits[key];else $(id).value=edits[key];}$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('voice-volume-label').hidden=!project.files.includes('mic');$('noise').disabled=!project.files.includes('mic');$('camera-settings').hidden=!project.files.includes('camera');$('caption-count').textContent=edits.captions.length?`${edits.captions.length} captions · timed to the original`:'No captions imported.';const length=keptSegments(edits).reduce((s,r)=>s+(r.end-r.start)/edits.speed,0);$('finished-length').textContent=`Finished length: ${time(length)}`;renderRanges();layout();syncAudio();drawTimeline();}
action('undo',()=>{if(!history.length)return;future.push(copy(edits));edits=history.pop();refresh();return saveNow();});action('redo',()=>{if(!future.length)return;history.push(copy(edits));edits=future.pop();refresh();return saveNow();});
function selection(){let start=Number($('range-start').value),end=Number($('range-end').value);start=Math.max(0,Math.min(project.duration,start));end=Math.max(0,Math.min(project.duration,end));if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error('Choose an end time after the start time.');return {start,end};}
function addRange(action){const r=selection();changed(()=>edits.ranges.push({...r,id:crypto.randomUUID(),action,scope:'all',label:'Selected moment',enabled:true}));}
action('mute-range',()=>addRange('mute'));action('cut-range',()=>addRange('cut'));action('use-playhead',()=>{$('range-start').value=video.currentTime.toFixed(2);$('range-end').value=Math.min(project.duration,video.currentTime+2).toFixed(2);drawTimeline();});
for(const id of ['range-start','range-end'])$(id).oninput=drawTimeline;
function renderRanges(){$('edit-list').replaceChildren();$('edit-count').textContent=edits.ranges.filter(r=>r.enabled).length;if(!edits.ranges.length){const p=document.createElement('p');p.className='empty-edits';p.textContent='No edits yet. Select a sound above, or run sound detection.';$('edit-list').append(p);}for(const r of [...edits.ranges].sort((a,b)=>a.start-b.start)){const row=document.createElement('div');row.className='edit-row';const check=document.createElement('input');check.type='checkbox';check.checked=r.enabled;check.setAttribute('aria-label',`Apply ${r.label}`);check.onchange=()=>changed(()=>r.enabled=check.checked);const label=document.createElement('div');label.className='edit-details';const b=document.createElement('b'),small=document.createElement('small');b.textContent=r.label;small.textContent=`${r.start.toFixed(2)}–${r.end.toFixed(2)}s${r.enabled?'':' · Review before applying'}`;label.append(b,small);const mode=document.createElement('select');mode.add(new Option('Mute sound','mute'));mode.add(new Option('Cut moment','cut'));mode.value=r.action;mode.onchange=()=>changed(()=>r.action=mode.value);mode.setAttribute('aria-label','Edit action');const scope=document.createElement('select');scope.add(new Option('All sound','all'));scope.add(new Option(project.files.includes('mic')?'Microphone only':'Video sound','voice'));scope.value=r.scope;scope.disabled=r.action==='cut';scope.setAttribute('aria-label','Sound track');scope.onchange=()=>changed(()=>r.scope=scope.value);const listen=document.createElement('button');listen.className='text-button';listen.textContent='Listen';listen.onclick=()=>{$('preview-original').checked=true;previewStop=Math.min(project.duration,r.end+.7);seek(Math.max(0,r.start-.7));play().catch(e=>toast(e.message));};const remove=document.createElement('button');remove.className='text-button';remove.textContent='Remove';remove.onclick=()=>changed(()=>edits.ranges=edits.ranges.filter(x=>x.id!==r.id));row.append(check,label,mode,scope,listen,remove);$('edit-list').append(row);}}
async function scan(){stopPlayback();await saveNow();let result;try{result=await api('sound:scan',project.id);}catch(e){toast(e.message);return;}project.scan=result.scan;changed(()=>{for(const r of result.scan){const id=`sound-${r.start}-${r.end}`;if(!edits.ranges.some(x=>x.id===id))edits.ranges.push({id,start:r.start,end:r.end,label:`Possible ${r.label.toLowerCase()}${r.voiceNearby?' · speech nearby':''}`,action:'mute',scope:'voice',enabled:r.suggested});}});$('scan-note').textContent=`${result.scan.length} possible interruptions found in the first 60 minutes. Checked suggestions will be muted. Listen before exporting; detection can miss sounds or flag speech.`;}
action('scan',scan);action('captions-import',async()=>{const captions=await api('captions:import');if(captions)changed(()=>edits.captions=captions);});action('captions-clear',()=>changed(()=>edits.captions=[]));
function original(){return $('preview-original').checked;}
function seek(t){video.currentTime=Math.max(0,Math.min(project.duration,t));syncAudio(true);drawTimeline();}
function syncAudio(force=false){if(!edits)return;const t=video.currentTime,rate=original()?1:edits.speed;video.playbackRate=rate;const active=original()?[]:edits.ranges.filter(r=>r.enabled&&r.action==='mute'&&t>=r.start&&t<=r.end);video.muted=active.some(r=>r.scope==='all'||!project.files.includes('mic'));video.volume=original()?1:Math.min(1,edits.systemVolume);voice.muted=active.length>0;voice.volume=original()?1:Math.min(1,edits.voiceVolume);for(const media of [voice,camera]){media.playbackRate=rate;if(media.getAttribute('src')&&(force||Math.abs(media.currentTime-t)>.12))try{media.currentTime=t;}catch{}}layout();}
async function play(){if(!project)return;if(!original()){const segments=keptSegments(edits);if(!segments.length)throw new Error('Restore part of the video before playing.');const next=segments.find(s=>s.end>video.currentTime);if(video.currentTime<edits.start||!next)seek(segments[0].start);else if(video.currentTime<next.start)seek(next.start);}syncAudio(true);await video.play();for(const m of [voice,camera])if(m.getAttribute('src'))m.play().catch(()=>{});$('play').textContent='Ⅱ Pause';}
action('play',()=>{previewStop=null;return video.paused?play():stopPlayback();});$('preview-original').onchange=()=>{previewStop=null;syncAudio(true);};$('scrub').oninput=()=>seek(Number($('scrub').value));video.onloadedmetadata=()=>{if(project){seek(edits.start);layout();}};video.onended=stopPlayback;video.onerror=()=>toast('This video could not play. Try importing an H.264 MP4 or VP8/VP9 WebM.');video.ontimeupdate=()=>{if(!project)return;const t=video.currentTime;if(!video.paused){if(previewStop!==null&&t>=previewStop){previewStop=null;stopPlayback();}else if(!original()){const next=keptSegments(edits).find(s=>s.end>t+.015);if(!next){stopPlayback();}else if(t<next.start)seek(next.start);}}$('scrub').value=video.currentTime;$('play-clock').textContent=`${time(video.currentTime)} / ${time(project.duration)}`;syncAudio();drawTimeline();};video.onpause=()=>{voice.pause();camera.pause();$('play').textContent='▶ Play edit';};
function outputTime(t){let n=0;for(const s of keptSegments(edits)){if(t>=s.end)n+=(s.end-s.start)/edits.speed;else if(t>s.start){n+=(t-s.start)/edits.speed;break;}}return n;}
function layout(){if(!edits)return;const stage=$('stage');stage.style.aspectRatio=edits.aspect==='vertical'?'9/16':edits.aspect==='square'?'1':'16/9';stage.style.background=edits.background;stage.style.maxWidth=(510*(edits.aspect==='vertical'?9/16:edits.aspect==='square'?1:16/9))+'px';const w=stage.clientWidth,h=stage.clientHeight,ratio=(video.videoWidth||project.screenInfo.width)/(video.videoHeight||project.screenInfo.height),iw=w*(1-edits.padding*2),ih=h*(1-edits.padding*2),fw=Math.min(iw,ih*ratio),fh=fw/ratio;$('screen-frame').style.width=fw+'px';$('screen-frame').style.height=fh+'px';video.style.transform=`scale(${edits.zoom})`;camera.hidden=!edits.camera||!project.files.includes('camera');const size=Math.min(w,h)*edits.cameraSize,margin=Math.min(w,h)*.03;Object.assign(camera.style,{width:size+'px',height:size+'px',top:edits.cameraCorner[0]==='t'?margin+'px':'auto',bottom:edits.cameraCorner[0]==='b'?margin+'px':'auto',left:edits.cameraCorner[1]==='l'?margin+'px':'auto',right:edits.cameraCorner[1]==='r'?margin+'px':'auto'});$('title-preview').textContent=outputTime(video.currentTime)<4?edits.title:'';$('caption-preview').textContent=edits.captions.filter(c=>c.start<=video.currentTime&&c.end>video.currentTime).map(c=>c.text).join('\n');}
new ResizeObserver(layout).observe($('stage'));
function drawTimeline(){if(!project)return;const canvas=$('timeline'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,D=project.duration;ctx.clearRect(0,0,W,H);ctx.fillStyle='#e8efec';ctx.fillRect(0,0,W,H);ctx.fillStyle='#85a89b';for(let i=0;i<peaks.length;i++){const height=Math.max(2,peaks[i]*H*.8);ctx.fillRect(i/peaks.length*W,(H-height)/2,Math.max(1,W/peaks.length),height);}for(const r of edits.ranges){ctx.fillStyle=!r.enabled?'#737b7520':r.action==='cut'?'#b7514055':'#33a87955';ctx.fillRect(r.start/D*W,0,(r.end-r.start)/D*W,H);}const a=Number($('range-start').value),b=Number($('range-end').value);ctx.strokeStyle='#173e35';ctx.lineWidth=2;ctx.strokeRect(a/D*W,2,(b-a)/D*W,H-4);ctx.fillStyle='#132f29';ctx.fillRect(video.currentTime/D*W,0,2,H);if(!peaks.length){ctx.font='18px sans-serif';ctx.fillText('Timeline · select a moment',20,55);}}
let drag=null;const timeline=$('timeline');const at=e=>Math.max(0,Math.min(project.duration,(e.clientX-timeline.getBoundingClientRect().left)/timeline.getBoundingClientRect().width*project.duration));timeline.onpointerdown=e=>{if(!project)return;drag=at(e);timeline.setPointerCapture(e.pointerId);$('range-start').value=drag.toFixed(2);$('range-end').value=Math.min(project.duration,drag+.1).toFixed(2);seek(drag);};timeline.onpointermove=e=>{if(drag===null)return;const end=at(e);$('range-start').value=Math.min(drag,end).toFixed(2);$('range-end').value=Math.max(drag,end).toFixed(2);drawTimeline();};timeline.onpointerup=()=>drag=null;timeline.onpointercancel=()=>drag=null;
async function exportEdit(draft){stopPlayback();await saveNow();if(draft){$('rendered-video').pause();$('rendered-video').removeAttribute('src');$('rendered-video').load();}const result=await api('export',project.id,copy(edits),draft);if(!result)return;if(draft){$('rendered-video').src=result.url;$('preview-dialog').showModal();}else toast('Your MP4 is ready. The original recording is unchanged.');}
action('export',()=>exportEdit(false));action('render-preview',()=>exportEdit(true));action('close-preview',()=>{$('rendered-video').pause();$('preview-dialog').close();});$('preview-dialog').addEventListener('close',()=>$('rendered-video').pause());document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)&&!$('editor-view').hidden&&!document.querySelector('dialog[open]')){e.preventDefault();$('play').click();}});
view('home');listProjects().catch(e=>toast(e.message));devices().catch(()=>{});
