'use strict';
const byId=id=>document.getElementById(id);let checking=false;
function resetDownloads(){for(const platform of ['mac','windows']){const link=byId(platform+'-download');link.removeAttribute('href');link.setAttribute('aria-disabled','true');link.textContent=(platform==='mac'?'Mac':'Windows')+' ZIP not published yet';byId(platform+'-detail').textContent='The ZIP will appear after a '+(platform==='mac'?'Mac':'Windows')+' build is published.';}byId('mac-dmg').hidden=true;byId('mac-dmg').removeAttribute('href');}
async function checkDownloads(){if(checking)return;checking=true;byId('retry').disabled=true;resetDownloads();byId('release-status').textContent='Checking which app downloads are available.';
try{const response=await fetch('https://api.github.com/repos/gopalbogati/Cleartake/releases?per_page=30',{headers:{Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Release lookup failed');const release=window.ClearTakeReleases.selectRelease(await response.json());
if(!release){byId('release-version').textContent='App downloads coming soon';byId('release-status').textContent='No app ZIP release has been published yet. You can download the source and build it yourself.';return;}
byId('release-version').textContent='v'+release.version+(release.preview?' · Development preview':'');byId('release-status').textContent=release.preview?'Development build. Read the release notes for testing and signing status before installing.':'Choose your operating system below. Installation details are in the release notes.';byId('release-link').href=release.url;
for(const platform of ['mac','windows']){const asset=release.assets[platform];if(!asset)continue;const link=byId(platform+'-download');link.href=asset.url;link.removeAttribute('aria-disabled');link.textContent='Download '+(platform==='mac'?'Mac':'Windows')+' ZIP ↓';byId(platform+'-detail').textContent=`v${release.version} · ${(asset.size/1024/1024).toFixed(0)} MB · ${platform==='mac'?'Apple Silicon':'Windows x64'}`;}
if(release.assets.dmg){byId('mac-dmg').href=release.assets.dmg.url;byId('mac-dmg').hidden=false;}
}catch{byId('release-version').textContent='Release check unavailable';byId('release-status').textContent='Could not check downloads right now. Open All releases below, or try again.';}finally{checking=false;byId('retry').disabled=false;}}
byId('retry').addEventListener('click',checkDownloads);fetch('version.json').then(r=>r.ok?r.json():null).then(data=>{if(data&&/^\d+\.\d+\.\d+$/.test(data.version))byId('source-version').textContent=data.version;}).catch(()=>{});checkDownloads();
